#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname exago_cmdline -pa $EXAGO_PATH

main(["erl"]) ->
    audit_server:start(),
    start_shell(),
    wait_for_exit(),
    audit_server:stop();

main(["gui"]) ->
    wx_ui:start(),
    start_shell(),
    wait_for_exit();

main(["run", Module, Fun | Args]) ->
    ConfRecord = erlang:apply(list_to_atom(Module), list_to_atom(Fun), Args),
    Pid = self(),
    spawn_link(fun() -> 
audit:run(ConfRecord),
Pid ! {'EXIT', self(), ok}
end),
    wait_for_exit();

main(["run", Filename]) ->
    audit_server:start(),
    audit_server:load(Filename),
    audit_server:run(), 
    ok;

main(_) ->
    usage().
        

start_shell() ->
    process_flag(trap_exit, true),
    link(shell:start()).

wait_for_exit() ->
    receive
	{'EXIT', _Pid, _Reason} ->
	    ok
    end.
    
usage() ->
    io:format("usage:\n"),
    io:format("  exago erl | gui | run Module Fun [Arg1 Arg2 ...] | run Filename\n"),
    halt(1).

