#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname exago_cmdline -pa $EXAGO_PATH

main([Module, Fun | Args]) ->
    ConfRecord = erlang:apply(list_to_atom(Module), list_to_atom(Fun), Args),
    Pid = self(),
    spawn_link(fun() -> 
exago:run(ConfRecord),
Pid ! {'EXIT', self(), ok}
end),
    wait_for_exit();

main(_) ->
    usage().

wait_for_exit() ->
    receive
	{'EXIT', _Pid, _Reason} ->
	    ok
    end.
    
usage() ->
    io:format("usage:\n"),
    io:format("  exago Module Fun [Arg1 Arg2 ...]\n"),
    halt(1).

